language: python
services:
  - docker
before_install:
  - mv secrets-example secrets.yaml
  - docker pull esphome/esphome
  - mkdir fonts && wget -q https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Regular.ttf -O fonts/FiraCode-Regular.ttf

script:
  - docker run --rm -v "${PWD}":/config -it --entrypoint /usr/bin/find esphome/esphome . -maxdepth 1 -type f -name "*.yaml" -and -not -name "secrets.yaml" -exec esphome {} config \;

