substitutions:
  devicename: bathroom_esp
  
esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret bathroom_esp_ip
    gateway: !secret gateway
    subnet: !secret subnet

i2c:
  scl: D1
  sda: D2

sensor:
  - platform: sht3xd
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    address: 0x44
    update_interval: 10s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
