esphome:
  name: entrance_door
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssida
  password: !secret wifi_ssid

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

status_led:
  pin: D4

dallas:
  - pin: D2

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: False
    name: "Entrance Door"
    device_class: door

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor

  - platform: dallas
    address: !secret entrance_door_dallas_sensor_address
    name: "Entrance Door Temperature"
