esphome:
  name: entrance_door
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret entrance_door_ip
    gateway: !secret gateway
    subnet: !secret subnet

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

dallas:
  - pin: D2

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: False
    name: "Entrance Door"
    device_class: door

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor

  - platform: dallas
    address: !secret entrance_door_dallas_sensor_address
    name: "Entrance Door Temperature"
