substitutions:
  devicename: kitchen_lights

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret kitchen_lights
    gateway: !secret gateway
    subnet: !secret subnet

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: monochromatic
    name: "Kitchen Lights"
    output: output_kitchen_lights

output:
  - platform: esp8266_pwm
    id: output_kitchen_lights
    pin: GPIO3
