substitutions:
  devicename: workstation

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret workstation_ip
    gateway: !secret gateway
    subnet: !secret subnet

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D7
  scl: D6
  scan: False

light:
  - platform: monochromatic
    name: "Workstation Lights"
    id: led
    output: output_workstation_light
    
binary_sensor:
  - platform: gpio
    pin: D2
    name: "Motion Sensor"
    device_class: motion

  - platform: gpio
    pin: D8
    id: button
    name: "Workstation Button"
    on_click:
      min_length: 50ms
      max_length: 200ms
      then:
        - light.toggle: led
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: usb
        - switch.turn_on: hdmi
        - delay: 100ms
        - switch.turn_off: hdmi
sensor:
  - platform: bh1750
    name: "Workstation Illuminance"
    address: 0x23
    update_interval: 60s

switch:
  - platform: gpio
    name: "HDMI swich"
    id: hdmi
    pin: D0
    icon: "mdi:monitor"
    restore_mode: ALWAYS_OFF
    
  - platform: gpio
    name: "USB swich"
    id: usb
    restore_mode: RESTORE_DEFAULT_OFF
    pin: D5
    
output:
  - platform: esp8266_pwm
    id: output_workstation_light
    pin: D1

  - platform: gpio
    id: output_workstation_hdmi
    pin: D3
    
